# Generated by Django 4.2.4 on 2023-09-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoLearn', '0002_initial'),
    ]

    operations = [
    ]
