# Generated by Django 4.2.4 on 2023-09-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoLearn', '0003_auto_20230924_1644'),
    ]

    operations = [
    ]
