# Generated by Django 4.2.4 on 2023-09-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoLearn', '0004_auto_20230925_1314'),
    ]

    operations = [
    ]
